/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "Government",
      collapsed: false,
      items: [
        "city-hall",
        "city-council",
        "city-maps",
        "parks-and-recreation",
        "information-technology",
      ],
    },
    {
      type: "category",
      label: "About",
      collapsed: false,
      items: ["quick-facts", "history"],
    },
  ],
  parksSidebar: [
    {
      type: "category",
      label: "Parks",
      collapsed: false,
      items: [
        "parks/wamapokestone-park",
        "parks/sullivan-street-pit",
        "parks/circle-park",
        "parks/smallest-park",
      ],
    },
  ],
};

module.exports = sidebars;
